### ISSUE TITLE
Perl Critic thinks a simple script is a module

### ISSUE THREAD

**Issue by fjossandon** [Perl-Critic/Perl-Critic#629]
Even if a script file has the shebang line and uses ".pl" file extension, Perl Critic will treat it like a module if the shebang line is not the very first line. In this example, there is a small comment line before the shebang, so the "Code not contained in explicit package" and "Module does not end with "1;"" warnings are triggered at severity level 4. 

Example code:

``` Perl
#################################
#     Author:  foobar
#################################

#!/usr/bin/perl

use strict;
use warnings;

my $foo = 4;
my $bar = 7;
my $foobar = $foo + $bar;

print "$foobar\n";
exit;
```

I saw that Perl/Critic/Document.pm subroutine "_determine_is_module" have 2 lines that look for shebang and file extesion:

``` Perl
    return $FALSE if shebang_line($self);
    return $FALSE if defined $file_name && $file_name =~ m/ [.] PL \z /smx;
```

The second line have a problem because the match is case sensitive and a ".pl" extension does not match, so the 'i' modifier should be added to the regex. Then the first line subroutine "shebang_line" seems that only looks for the shebang in the very first line of the script, when it could look a little further by skipping empty lines and comment lines at the beginning of the file until it reach the first code line (like "if ($line =~ m/^\s*$/ or $line =~ m/^#/) {next;} ).

Out of the 2 lines mentioned above, I think that the "i" modifier should definitely be added to the regex, since scripts using the lowercase extension is quite common.

Best regards.

**Comment by thaljef** [comment]
It sounds like you're writing for Windows, which doesn't care about shebang lines. On Unix, only the first line is considered to be a shebang line. On any other line, `#!/usr/bin/perl` doesn't mean anything.

The `.PL` regex is deliberately capitalized for the sake of special files like `Makefile.PL` which are always scripts (not modules) but usually don't have a shebang line.

Otherwise, if the file doesn't have a shebang and its not one of the special `.PL` files, then Perl::Critic treats in like a module.

If you put your shebang in the right place, then Perl::Critic will do the right thing and your script will work on Unix the way it is supposed to.

Does that make sense?

**Comment by fjossandon** [comment]
You are correct, I usually code in Windows and I also usually run my scripts as "perl script.pl" in Windows and Linux. so the shebang location is not affecting me, so that's my mistake. But I think that this case is still a bug because Critic is treating the code like a module when it is not, so a user like me could ignore the warning instead of fixing the undetected portability problem you mention (the shebang location).

This is what I think would be most helpful for a user, let me know what you think. Since Critic already looks for the shebang line, if it does not find it in the very first line, it should continue looking for it until it reach the first code line (skipping the first lines as long as they are empty, filled with whitespace or are comment lines (/^\s*$/  or /^\s*#/) ). Then if the shebang is found (albeit displaced), first declare that is not a module, and then generate a level 5 DisplacedShebangLine warning like "shebang line is present but not located on line 1 (portability problem)". This on one hand would avoid applying the module-related warnings (that are not applicable in this case), and on the other hand would direct the user to correct the portability issue that he may not being aware of.

Now on the case-sensitive regex, I don't see how making it case-insensitive would be detrimental to the special ".PL" files, since they would still be matching the new regex, and modules use the ".pm" file extension. Can you explain me why it would be a bad idea?? Maybe I'm missing something??

**Comment by thaljef** [comment]
The lowercase `.pl` extension does not always indicate that a file is a script. Before Perl5 introduced the "Perl module" with `.pm` extensions, there were "Perl libraries" and they all had `.pl` extensions. From that point of view, Windows actually misuses the `.pl` extension. So that regex is not going to change.

But, I had forgotten that `perlcritic` also has a `--program-extensions` option that allows you control which file extensions are judged as programs rather than modules (you can also set that in your `.perlcriticrc` file). So that may be what you're looking for.

The `DisplacedShebangLine` policy is an interesting idea. I'll give that more thought.

Writing for both Windows and Unix is always a little awkward. Unix executables never have extensions because the user shouldn't have to know or care what language an application was written in. But since Windows doesn't understand shebang lines, it forces you to leak that information by adding the extension to the file.

My advice would be to put the shebang in the right place, remove the `.pl` extension from your scripts, and then write a native Windows batch file that invokes your code with the right interpreter. That way, you can just invoke it as `myapp` everywhere. But it has been a long time since I developed on Windows, so I'm not sure if that advice is applicable any more.

**Comment by fjossandon** [comment]
Ok, so ".PL" comes from historical reasons before Perl5. I agree on putting the shebang line in its correct place now that I'm aware of that, but I hope that you can implement the DisplacedShebangLine idea, since it would give the proper warning and avoid the unrelated Module warnings  (which can lead to confusion for the less experienced) after recognaizing it as a (faulty) script.

After digging around, I found the "--program-extensions" config in the .perlcriticrc example file, that will certainly help me for the time being, so I will start to experiment with it.

**Comment by dolmen** [comment]
Note that perl scripts converted to Windows batch files with `pl2bat` will have the she-bang not as the first line, but this is not an error. If this `DisplacedShebangLine` policy is created it will have to ignore `.bat` and `.cmd` files.

**Comment by fjossandon** [comment]
Closing my issue since it was decided that there would be no changes regarding the original case, and the new suggested policy did not gain enough traction
