### ISSUE TITLE
Modules::RequireNoMatchVarsWithUseEnglish and perl > 5.20

### ISSUE THREAD

**Issue by SparkeyG** [Perl-Critic/Perl-Critic#686]
With the improvements in use English that came with 5.20, should this be triggered for newer perls?

**Comment by petdance** [comment]
There are a few use cases here we've discussed.

* @SparkeyG only uses Perl > 5.20, and he wants to be able to use match variables like `$&` without Perl::Critic warning about it, because `$&` is not detrimental in his case.

* A CPAN author might have a module, and she wants to make sure that `$&` doesn't get accidentally in to her code, even if she's running Perl > 5.20, because her users might not be.

* A different CPAN author might have a module that only runs on 5.20 and above, and he wants to be able to use `$&` without warnings, just like @SparkeyG in the first use case.

**Comment by thaljef** [comment]
There is a utility method for determining the lowest applicable Perl version via a “use 5.xx” statement. There are several policies that use it to modulate their own behavior.
