### ISSUE TITLE
critic might crash on an empty file

### ISSUE THREAD

**Issue by spidamoo** [Perl-Critic/Perl-Critic#800]
I run Perl::Critic::Policy::Freenode::WarningsSwitch on a pm file which is just empty and it dies in PPI::Element->first_token with "Found empty PPI::Node while getting first token". Running critic on an empty file is silly of course but still I don't think it should just crash in this case.

**Comment by petdance** [comment]
I agree that Perl::Critic should not crash, but I'm not sure passing silently is the way to go, either, as your PR does.

I'd think that someone who is running critic on her codebase would want to know that one of the files had zero content.

**Comment by xsawyerx** [comment]
At `$work` we have a large codebase. We might find empty files. While we want to remove them (and work through it), we don't want this to just fatally crash the entire script that runs Perl::Critic on the code-base. If Perl::Critic is run via CI, we want that script to alert of empty file instead of saying "We couldn't check it. It crashed." It's not even an intended situation. It just crashes because of an empty PPI node. It's saying "We couldn't check it. It crashed because there was some empty PPI node."

I think if one wants to avoid empty files, that could be a policy. However, we cannot be unstable and crash because someone created an empty placeholder file, for example.

**Comment by petdance** [comment]
Of course not, nobody wants it to crash.

**Comment by clonezone** [comment]
Long standing P::C policy has been to only support files that parse. If the file is not valid code, it is not our problem.

**Comment by spidamoo** [comment]
One could argue that "not supporting" does not necessarily equal "pretend that this could not happen and ignore whatever happens because of it". "Refusing to process at all" (as in my PR) on the other hand fits into definition of "not supporting" IMO.
I agree that silently skipping is not a great way to deal with it though. Maybe add a warn there?

**Comment by petdance** [comment]
Sounds like it should be a policy that can be turned off and on.

**Comment by trwyant** [comment]
Does anything need to be done to Perl-Critic for this ticket? None of the core policies have a problem with empty files that I can determine -- at least I ran --brutal against an empty file and nothing bad happened. Maybe Perl::Critic::Policy::Freenode::WarningsSwitch needs work, but that's not part of the Perl-Critic distribution.

Unless this ticket is interpreted as asking Perl::Critic to field exceptions from policies, so that one rogue policy does not send an entire run down the tubes.

**Comment by petdance** [comment]
> Maybe Perl::Critic::Policy::Freenode::WarningsSwitch needs work, but that's not part of the Perl-Critic distribution.

Agreed.  This is an issue to take up with Perl::Critic::Policy::Freenode.
